# Generated by Django 3.0.4 on 2020-03-18 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Parts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=15)),
                ('name', models.CharField(max_length=50)),
                ('remarks', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PartsInOut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warehausing', models.IntegerField(default=0)),
                ('shipping', models.IntegerField(default=0)),
                ('input_date', models.DateTimeField(verbose_name='入庫日')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parts_manager.Location')),
                ('parts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parts_manager.Parts')),
            ],
        ),
    ]
