# Generated by Django 3.0.4 on 2020-03-18 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parts_manager', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partsinout',
            old_name='warehausing',
            new_name='warehousing',
        ),
    ]
