# Generated by Django 3.0.4 on 2020-03-19 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts_manager', '0002_auto_20200319_0725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parts',
            name='remarks',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
