# Generated by Django 3.0.4 on 2020-03-19 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts_manager', '0004_auto_20200319_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parts',
            name='remarks',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='備考'),
        ),
        migrations.AlterField(
            model_name='partsinout',
            name='input_date',
            field=models.DateTimeField(verbose_name='入力日'),
        ),
        migrations.AlterField(
            model_name='partsinout',
            name='shipping',
            field=models.IntegerField(default=0, verbose_name='出庫日'),
        ),
        migrations.AlterField(
            model_name='partsinout',
            name='warehousing',
            field=models.IntegerField(default=0, verbose_name='入庫日'),
        ),
    ]
