# Generated by Django 3.0.4 on 2020-03-19 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parts_manager', '0005_auto_20200319_1533'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partsinout',
            options={'ordering': ['parts__name']},
        ),
    ]
