# Generated by Django 3.0.4 on 2020-03-23 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts_manager', '0006_auto_20200319_1559'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partsinout',
            options={'ordering': ['parts__code']},
        ),
        migrations.AlterField(
            model_name='partsinout',
            name='input_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='入力日'),
        ),
        migrations.AlterField(
            model_name='partsinout',
            name='shipping',
            field=models.IntegerField(default=0, verbose_name='出庫数'),
        ),
        migrations.AlterField(
            model_name='partsinout',
            name='warehousing',
            field=models.IntegerField(default=0, verbose_name='入庫数'),
        ),
    ]
