# Generated by Django 3.0.4 on 2020-03-24 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parts_manager', '0008_auto_20200324_1028'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partsinout',
            old_name='input_date',
            new_name='last_updated',
        ),
    ]
