# Generated by Django 3.0.4 on 2020-03-24 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts_manager', '0010_auto_20200324_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partsinout',
            name='last_updated',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
