# Generated by Django 3.0.4 on 2020-03-25 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parts_manager', '0013_auto_20200325_1400'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partsinout',
            old_name='input_date',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='partsinout',
            old_name='last_updated',
            new_name='updated',
        ),
    ]
