# Generated by Django 3.0.4 on 2020-03-25 05:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('parts_manager', '0014_auto_20200325_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partsinout',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日'),
        ),
        migrations.AlterField(
            model_name='partsinout',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='更新日'),
        ),
    ]
