# Generated by Django 3.0.4 on 2020-03-25 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts_manager', '0015_auto_20200325_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partsinout',
            name='shipping',
            field=models.IntegerField(default=0, verbose_name='出庫数'),
        ),
        migrations.AlterField(
            model_name='partsinout',
            name='warehousing',
            field=models.IntegerField(default=0, verbose_name='入庫数'),
        ),
    ]
